export 'package:feriavirtual/screens/authScreen.dart';
export 'package:feriavirtual/screens/homePage.dart';
export 'package:feriavirtual/screens/homePageLogged.dart';
export 'package:feriavirtual/screens/mainPage.dart';
export 'package:feriavirtual/screens/mainPageLogged.dart';
export 'package:feriavirtual/screens/test.dart';
export 'package:feriavirtual/screens/university.dart';
export 'package:feriavirtual/screens/universities.dart';
export '../screens/TestFormulario.dart';
